BaseUrl: "http://yet.unresolved.xyz"
LanguageCode: "en-us"
Title: "QiHuan"

params:
  ProfilePicture: "pathOrUrlToImage"
  links:
    Home   : "/"
    Android : "/android/"
    后台 : "/back/"
    关于 : "/about"